version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install --frozen-lockfile
            - run: yarn compile
            - run: yarn lint
            - run: yarn prettier:check
            # Tests excluded for now
            #- run: yarn test
workflows:
  build-and-test:
    jobs:
      - build-and-test
