on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        # TODO jari: run on other platforms as well later
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - run: sudo apt update
      - run: sudo apt install software-properties-common
      - run: sudo apt-add-repository --yes --update ppa:ansible/ansible
      - run: sudo apt install ansible

      - run: yarn install --frozen-lockfile

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: yarn test
